<?php

namespace Tests\Feature;

use App\Exports\UsersExport;
use App\Imports\UsersImport;
use PHPUnit\Framework\Attributes\Test;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Hash;
use Maatwebsite\Excel\Facades\Excel;
use Tests\TestCase;

class UserControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Helper: create and log in an admin user.
     */
    protected function actingAsAdmin(): User
    {
        $admin = User::factory()->create([
            'role' => 'admin',
        ]);

        $this->actingAs($admin);

        return $admin;
    }

    #[Test]
    public function it_displays_the_users_index_page()
    {
        $this->actingAsAdmin();

        User::factory()->count(3)->create();

        $response = $this->get(route('users.index'));

        $response->assertStatus(200);
        $response->assertViewIs('users.index');
        $response->assertViewHas('users', function ($users) {
            // should match how many are in DB
            return $users->count() === User::count();
        });
    }
    #[Test]
    public function it_displays_the_create_user_form()
    {
        $this->actingAsAdmin();

        $response = $this->get(route('users.create'));

        $response->assertStatus(200);
        $response->assertViewIs('users.create');
    }

    #[Test]
    public function it_stores_a_new_user_with_random_password()
    {
        $this->actingAsAdmin();

        $data = [
            'name' => 'John Doe',
            'role' => 'worker',
        ];

        $response = $this->post(route('users.store'), $data);

        $response->assertRedirect(route('users.index'));

        $this->assertDatabaseHas('users', [
            'name' => 'John Doe',
            'role' => 'worker',
        ]);

        $user = User::where('name', 'John Doe')->first();
        $this->assertNotNull($user);

        // visible_password generated by controller
        $this->assertNotNull($user->visible_password);
        $this->assertEquals(8, strlen($user->visible_password));
        $this->assertTrue(Hash::check($user->visible_password, $user->password));
    }

    #[Test]
    public function it_validates_store_request()
    {
        $this->actingAsAdmin();

        $response = $this->post(route('users.store'), [
            'name' => '',           // invalid
            'role' => 'something',  // invalid
        ]);

        $response->assertSessionHasErrors(['name', 'role']);
    }

    #[Test]
    public function it_displays_the_edit_form_for_a_user()
    {
        $this->actingAsAdmin();

        $user = User::factory()->create();

        $response = $this->get(route('users.edit', $user));

        $response->assertStatus(200);
        $response->assertViewIs('users.edit');
        $response->assertViewHas('user', function ($viewUser) use ($user) {
            return $viewUser->id === $user->id;
        });
    }

    #[Test]
    public function it_updates_a_user_without_changing_password_when_password_is_empty()
    {
        $this->actingAsAdmin();

        $user = User::factory()->create([
            'name' => 'Old Name',
            'role' => 'worker',
            'password' => Hash::make('oldpassword'),
            'visible_password' => 'oldpassword',
        ]);

        $response = $this->put(route('users.update', $user), [
            'name' => 'New Name',
            'role' => 'admin',
            'password' => '',
            'password_confirmation' => '',
        ]);

        $response->assertRedirect(route('users.index'));

        $user->refresh();

        $this->assertEquals('New Name', $user->name);
        $this->assertEquals('admin', $user->role);
        // password should remain oldpassword
        $this->assertTrue(Hash::check('oldpassword', $user->password));
        $this->assertEquals('oldpassword', $user->visible_password);
    }

    #[Test]
    public function it_updates_a_user_and_changes_password_when_provided()
    {
        $this->actingAsAdmin();

        $user = User::factory()->create([
            'password' => Hash::make('oldpassword'),
            'visible_password' => 'oldpassword',
        ]);

        $response = $this->put(route('users.update', $user), [
            'name' => 'Updated User',
            'role' => 'admin',
            'password' => 'newpassword',
            'password_confirmation' => 'newpassword',
        ]);

        $response->assertRedirect(route('users.index'));

        $user->refresh();

        $this->assertEquals('Updated User', $user->name);
        $this->assertEquals('admin', $user->role);
        $this->assertTrue(Hash::check('newpassword', $user->password));
        $this->assertEquals('newpassword', $user->visible_password);
    }

    #[Test]
    public function it_validates_update_request()
    {
        $this->actingAsAdmin();

        $user = User::factory()->create();

        $response = $this->put(route('users.update', $user), [
            'name' => '',
            'role' => 'invalid-role',
        ]);

        $response->assertSessionHasErrors(['name', 'role']);
    }

    #[Test]
    public function it_deletes_a_user()
    {
        $this->actingAsAdmin();

        $user = User::factory()->create();

        $response = $this->delete(route('users.destroy', $user));

        $response->assertRedirect(route('users.index'));

        $this->assertDatabaseMissing('users', [
            'id' => $user->id,
        ]);
    }

    #[Test]
    public function it_imports_users_from_excel_file()
    {
        $this->actingAsAdmin();

        Excel::fake();

        $file = UploadedFile::fake()->create('users.xlsx');

        $response = $this->post(route('users.import'), [
            'import_file' => $file,
        ]);

        $response->assertRedirect(route('users.index'));
        $response->assertSessionHas('success', 'Lietotāji veiksmīgi importēti.');

        
    }
    #[Test]
    public function it_validates_import_request()
    {
        $this->actingAsAdmin();

        $response = $this->post(route('users.import'), [
            // no file
        ]);

        $response->assertSessionHasErrors(['import_file']);
    }

    #[Test]
    public function it_exports_users_to_excel_file()
    {
        $this->actingAsAdmin();

        Excel::fake();

        $response = $this->get(route('users.export'));

        // When Excel::fake() is used, the response is faked too,
        // so we usually just assert the download was triggered.
        Excel::assertDownloaded('users.xlsx', function (UsersExport $export) {
            return true;
        });
    }
}
